schema_version = 1

[controller]
control_interval_us = 5000
initial_max_stream_data = 16
automatic_receive_window = 1048576
max_chaff_streams = 5
low_watermark = 1000000
use_empty_resources = false
max_stream_data_excess = 1000
max_udp_payload_size = 1450
drop_unsatisfied_events = false
keep_alive_lead_time_us = 100000
tail_wait_us = 0

[front]
n_client_packets = 900
n_server_packets = 1200
packet_size = 1450
peak_minimum_seconds = 0.1
peak_maximum_seconds = 2.5

[tamaraw]
incoming_interval_us = 5000
outgoing_interval_us = 20000
packet_size = 1450
modulo = 100
